(function(){var p,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function r(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
var ea=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if(typeof Reflect!="undefined"&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){e===void 0&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}(),fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ka={};try{ka.__proto__=ia;ha=ka.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=fa;
function u(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ga=b.prototype}function ma(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ma(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function na(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function x(){this.u=!1;this.l=null;this.o=void 0;this.g=1;this.i=this.m=0;this.A=this.h=null}
function oa(a){if(a.u)throw new TypeError("Generator is already running");a.u=!0}x.prototype.C=function(a){this.o=a};function qa(a,b){a.h={aa:b,ca:!0};a.g=a.m||a.i}x.prototype.getNextAddressJsc=function(){return this.g};x.prototype.getYieldResultJsc=function(){return this.o};x.prototype.return=function(a){this.h={return:a};this.g=this.i};x.prototype["return"]=x.prototype.return;x.prototype.K=function(a){this.h={F:a};this.g=this.i};x.prototype.jumpThroughFinallyBlocks=x.prototype.K;
x.prototype.v=function(a,b){this.g=b;return{value:a}};x.prototype.yield=x.prototype.v;x.prototype.S=function(a,b){a=v(a);var c=a.next();na(c);if(c.done)this.o=c.value,this.g=b;else return this.l=a,this.v(c.value,b)};x.prototype.yieldAll=x.prototype.S;x.prototype.F=function(a){this.g=a};x.prototype.jumpTo=x.prototype.F;x.prototype.D=function(){this.g=0};x.prototype.jumpToEnd=x.prototype.D;x.prototype.P=function(a,b){this.m=a;b!=void 0&&(this.i=b)};x.prototype.setCatchFinallyBlocks=x.prototype.P;
x.prototype.R=function(a){this.m=0;this.i=a||0};x.prototype.setFinallyBlock=x.prototype.R;x.prototype.O=function(a,b){this.g=a;this.m=b||0};x.prototype.leaveTryBlock=x.prototype.O;x.prototype.H=function(a){this.m=a||0;a=this.h.aa;this.h=null;return a};x.prototype.enterCatchBlock=x.prototype.H;x.prototype.I=function(a,b,c){c?this.A[c]=this.h:this.A=[this.h];this.m=a||0;this.i=b||0};x.prototype.enterFinallyBlock=x.prototype.I;
x.prototype.N=function(a,b){b=this.A.splice(b||0)[0];(b=this.h=this.h||b)?b.ca?this.g=this.m||this.i:b.F!=void 0&&this.i<b.F?(this.g=b.F,this.h=null):this.g=this.i:this.g=a};x.prototype.leaveFinallyBlock=x.prototype.N;x.prototype.J=function(a){return new sa(a)};x.prototype.forIn=x.prototype.J;function sa(a){this.i=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}sa.prototype.h=function(){for(;this.g.length>0;){var a=this.g.pop();if(a in this.i)return a}return null};
sa.prototype.getNext=sa.prototype.h;function ta(a){this.g=new x;this.h=a}function ua(a,b){oa(a.g);var c=a.g.l;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return wa(a)}function va(a,b,c,d){try{var e=b.call(a.g.l,c);na(e);if(!e.done)return a.g.u=!1,e;var h=e.value}catch(f){return a.g.l=null,qa(a.g,f),wa(a)}a.g.l=null;d.call(a.g,h);return wa(a)}
function wa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.u=!1,{value:b.value,done:!1}}catch(c){a.g.o=void 0,qa(a.g,c)}a.g.u=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.ca)throw b.aa;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){oa(a.g);a.g.l?b=va(a,a.g.l.next,b,a.g.C):(a.g.C(b),b=wa(a));return b};this.throw=function(b){oa(a.g);a.g.l?b=va(a,a.g.l["throw"],b,a.g.C):(qa(a.g,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};this[Symbol.iterator]=function(){return this}}function ya(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function za(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}r("Reflect",function(a){return a?a:{}});r("Reflect.construct",function(){return ea});r("Reflect.setPrototypeOf",function(a){return a?a:la?function(b,c){try{return la(b,c),!0}catch(d){return!1}}:null});
r("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.g=h;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Aa(ma(this))}});return a});function Aa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
r("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.u=!1;var k=this.l();try{f(k.resolve,k.reject)}catch(g){k.reject(g)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(k){k(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var k=this;this.i(function(){k.m()})}this.g.push(f)};var e=da.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var k=0;k<f.length;++k){var g=
f[k];f[k]=null;try{g()}catch(l){this.l(l)}}}this.g=null};c.prototype.l=function(f){this.i(function(){throw f;})};b.prototype.l=function(){function f(l){return function(m){g||(g=!0,l.call(k,m))}}var k=this,g=!1;return{resolve:f(this.H),reject:f(this.m)}};b.prototype.H=function(f){if(f===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.J(f);else{a:switch(typeof f){case "object":var k=f!=null;break a;case "function":k=!0;break a;default:k=!1}k?this.D(f):this.o(f)}};
b.prototype.D=function(f){var k=void 0;try{k=f.then}catch(g){this.m(g);return}typeof k=="function"?this.K(k,f):this.o(f)};b.prototype.m=function(f){this.v(2,f)};b.prototype.o=function(f){this.v(1,f)};b.prototype.v=function(f,k){if(this.h!=0)throw Error("Cannot settle("+f+", "+k+"): Promise already settled in state"+this.h);this.h=f;this.i=k;this.h===2&&this.I();this.C()};b.prototype.I=function(){var f=this;e(function(){if(f.A()){var k=da.console;typeof k!=="undefined"&&k.error(f.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var f=da.CustomEvent,k=da.Event,g=da.dispatchEvent;if(typeof g==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof k==="function"?f=new k("unhandledrejection",{cancelable:!0}):(f=da.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return g(f)};b.prototype.C=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)h.h(this.g[f]);this.g=null}};var h=new c;
b.prototype.J=function(f){var k=this.l();f.U(k.resolve,k.reject)};b.prototype.K=function(f,k){var g=this.l();try{f.call(k,g.resolve,g.reject)}catch(l){g.reject(l)}};b.prototype.then=function(f,k){function g(q,t){return typeof q=="function"?function(y){try{l(q(y))}catch(B){m(B)}}:t}var l,m,n=new b(function(q,t){l=q;m=t});this.U(g(f,l),g(k,m));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.U=function(f,k){function g(){switch(l.h){case 1:f(l.i);break;case 2:k(l.i);break;
default:throw Error("Unexpected state: "+l.h);}}var l=this;this.g==null?h.h(g):this.g.push(g);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(k,g){g(f)})};b.race=function(f){return new b(function(k,g){for(var l=v(f),m=l.next();!m.done;m=l.next())d(m.value).U(k,g)})};b.all=function(f){var k=v(f),g=k.next();return g.done?d([]):new b(function(l,m){function n(y){return function(B){q[y]=B;t--;t==0&&l(q)}}var q=[],t=0;do q.push(void 0),t++,d(g.value).U(n(q.length-1),m),g=k.next();while(!g.done)})};
return b});r("Object.setPrototypeOf",function(a){return a||la});function Ba(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return Ba(this,function(b){return b})}});
r("WeakMap",function(a){function b(g){this.g=(k+=Math.random()+1).toString();if(g){g=v(g);for(var l;!(l=g.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(g){var l=typeof g;return l==="object"&&g!==null||l==="function"}function e(g){if(!w(g,f)){var l=new c;ba(g,f,{value:l})}}function h(g){var l=Object[g];l&&(Object[g]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),l=Object.seal({}),
m=new a([[g,2],[l,3]]);if(m.get(g)!=2||m.get(l)!=3)return!1;m.delete(g);m.set(l,4);return!m.has(g)&&m.get(l)==4}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var k=0;b.prototype.set=function(g,l){if(!d(g))throw Error("Invalid WeakMap key");e(g);if(!w(g,f))throw Error("WeakMap key fail: "+g);g[f][this.g]=l;return this};b.prototype.get=function(g){return d(g)&&w(g,f)?g[f][this.g]:void 0};b.prototype.has=function(g){return d(g)&&w(g,
f)&&w(g[f],this.g)};b.prototype.delete=function(g){return d(g)&&w(g,f)&&w(g[f],this.g)?delete g[f][this.g]:!1};return b});
r("Map",function(a){function b(){var k={};return k.B=k.next=k.head=k}function c(k,g){var l=k[1];return Aa(function(){if(l){for(;l.head!=k[1];)l=l.B;for(;l.next!=l.head;)return l=l.next,{done:!1,value:g(l)};l=null}return{done:!0,value:void 0}})}function d(k,g){var l=g&&typeof g;l=="object"||l=="function"?h.has(g)?l=h.get(g):(l=""+ ++f,h.set(g,l)):l="p_"+g;var m=k[0][l];if(m&&w(k[0],l))for(k=0;k<m.length;k++){var n=m[k];if(g!==g&&n.key!==n.key||g===n.key)return{id:l,list:m,index:k,entry:n}}return{id:l,
list:m,index:-1,entry:void 0}}function e(k){this[0]={};this[1]=b();this.size=0;if(k){k=v(k);for(var g;!(g=k.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var k=Object.seal({x:4}),g=new a(v([[k,"s"]]));if(g.get(k)!="s"||g.size!=1||g.get({x:4})||g.set({x:4},"t")!=g||g.size!=2)return!1;var l=g.entries(),m=l.next();if(m.done||m.value[0]!=k||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(k,g){k=k===0?0:k;var l=d(this,k);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=g:(l.entry={next:this[1],B:this[1].B,head:this[1],key:k,value:g},l.list.push(l.entry),this[1].B.next=l.entry,this[1].B=l.entry,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.entry&&k.list?(k.list.splice(k.index,1),k.list.length||delete this[0][k.id],k.entry.B.next=k.entry.next,
k.entry.next.B=k.entry.B,k.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].B=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).entry};e.prototype.get=function(k){return(k=d(this,k).entry)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=
function(k,g){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,k.call(g,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});r("Array.prototype.entries",function(a){return a?a:function(){return Ba(this,function(b,c){return[b,c]})}});r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push([d,b[d]]);return c}});r("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push(b[d]);return c}});
r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(k){return k};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});
r("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});r("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});r("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});r("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});r("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
r("String.prototype.startsWith",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var h=0;h<e&&c<d;)if(this[c++]!=b[h++])return!1;return h>=e}});
r("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});r("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});r("Array.prototype.values",function(a){return a?a:function(){return Ba(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var z=this||self;function Ca(a){var b=za.apply(1,arguments).filter(Boolean).join("&");if(!b)return a;var c=a.match(/[?&]adurl=/);return c?a.slice(0,c.index+1)+b+"&"+a.slice(c.index+1):a+(a.indexOf("?")<0?"?":"&")+b}function Da(a,b){return a===0?"ri=1":a===1?b?"ri=24":"ri=27":a===2?b?"ri=25":"ri=26":""}function Ea(a,b){return b?"&"+a+"="+encodeURIComponent(b):""}
function Fa(a){var b=a.url;a=a.oa;this.h=b;this.l=a;this.i=(new Date).getTime()-17040672E5;this.g={};for(var c=/[?&]([^&=]+)=([^&]*)/g;a=c.exec(b);)this.g[a[1]]=a[2]}function Ga(a,b){if(a.g.dsh==="1")return null;var c=a.g.ae;if(c==="1"){var d=a.g.adurl;if(d)try{return{version:3,V:decodeURIComponent(d),T:Ca(a.h,"act=1",Da(b,!0),Ha(a))}}catch(e){}}return c==="2"?{version:4,V:Ca(a.h,"dct=1","suid="+a.i,Da(b,!1)),T:Ca(a.h,"act=1",Da(b,!0),"suid="+a.i)}:null}
function Ia(a,b){return b===2?Ca(a.h,"ri=2"):b===0?Ca(a.h,"ri=16"):a.h}function Ha(a){a=a.l;if(!a)return"";var b=Ea("uap",a.platform)+Ea("uapv",a.platformVersion)+Ea("uafv",a.uaFullVersion)+Ea("uaa",a.architecture)+Ea("uam",a.model)+Ea("uab",a.bitness);a.fullVersionList&&(b+="&uafvl="+encodeURIComponent(a.fullVersionList.map(function(c){return encodeURIComponent(c.brand)+";"+encodeURIComponent(c.version)}).join("|")));a.wow64!=null&&(b+="&uaw="+Number(a.wow64));return b.slice(1)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function Ja(a){this.g=a}Ja.prototype.toString=function(){return this.g};var Ka=new Ja("about:invalid#zClosurez");function La(a){this.na=a}function A(a){return new La(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Ma=new La(function(a){return/^[^:]*([/?#]|$)/.test(a)}),Na=A("http"),Oa=A("https"),Pa=A("ftp"),Qa=A("mailto"),Ra=A("intent"),Sa=A("market"),Ta=A("itms"),Ua=A("itms-appss"),Va=[A("data"),Na,Oa,Qa,Pa,Ma],Wa=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Xa(a,b){if(b instanceof Ja)if(b instanceof Ja)b=b.g;else throw Error("");else b=Wa.test(b)?b:void 0;b!==void 0&&(a.href=b)};var Ya=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Za=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function $a(a,b){a:{for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return b<0?null:typeof a==="string"?a.charAt(b):a[b]};function ab(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function bb(a){z.setTimeout(function(){throw a;},0)};function cb(a){var b;a:{if(b=z.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};var db,eb;a:{for(var fb=["CLOSURE_FLAGS"],gb=z,ib=0;ib<fb.length;ib++)if(gb=gb[fb[ib]],gb==null){eb=null;break a}eb=gb}var jb=eb&&eb[748402147];db=jb!=null?jb:!0;function kb(){return cb("iPhone")&&!cb("iPod")&&!cb("iPad")};function lb(a){lb[" "](a);return a}lb[" "]=function(){};var nb=kb(),ob=cb("iPad");var pb=kb()||cb("iPod"),qb=cb("iPad");var rb={},sb=null;var tb=void 0;function ub(a){a=Error(a);ab(a,"warning");return a};function vb(){return typeof BigInt==="function"};var wb=typeof Symbol==="function"&&typeof Symbol()==="symbol";function xb(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var yb=xb("jas",void 0,!0),zb=xb(void 0,"0di"),Ab=xb(void 0,"0actk"),Bb=xb("m_m","Fa",!0);var Cb={ma:{value:0,configurable:!0,writable:!0,enumerable:!1}},Db=Object.defineProperties,C=wb?yb:"ma",Eb,Fb=[];E(Fb,7);Eb=Object.freeze(Fb);function Gb(a,b){wb||C in a||Db(a,Cb);a[C]|=b}function E(a,b){wb||C in a||Db(a,Cb);a[C]=b}function Hb(a){Gb(a,34);return a}function Ib(a){Gb(a,8192);return a};var Jb={};function F(a,b){return b===void 0?a.g!==Kb&&!!(2&(a.j[C]|0)):!!(2&b)&&a.g!==Kb}var Kb={};function Lb(a,b,c){this.g=a;this.h=b;this.i=c}Lb.prototype.next=function(){var a=this.g.next();a.done||(a.value=this.h.call(this.i,a.value));return a};Lb.prototype[Symbol.iterator]=function(){return this};var Mb=Object.freeze({});function Nb(a){a.Ea=!0;return a};var Ob=Nb(function(a){return typeof a==="number"}),Pb=Nb(function(a){return typeof a==="string"}),Qb=Nb(function(a){return typeof a==="boolean"}),Rb=Nb(function(a){return typeof a==="function"});var Sb=typeof z.BigInt==="function"&&typeof z.BigInt(0)==="bigint";function Tb(a){var b=a;if(Pb(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ob(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Sb?BigInt(a):a=Qb(a)?a?"1":"0":Pb(a)?a.trim()||"0":String(a)}var Zb=Nb(function(a){return Sb?a>=Ub&&a<=Vb:a[0]==="-"?Wb(a,Xb):Wb(a,Yb)}),Xb=Number.MIN_SAFE_INTEGER.toString(),Ub=Sb?BigInt(Number.MIN_SAFE_INTEGER):void 0,Yb=Number.MAX_SAFE_INTEGER.toString(),Vb=Sb?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Wb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var G=0,H=0;function $b(a){var b=a>>>0;G=b;H=(a-b)/4294967296>>>0}function ac(a){if(a<0){$b(-a);var b=v(bc(G,H));a=b.next().value;b=b.next().value;G=a>>>0;H=b>>>0}else $b(a)}function cc(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else vb()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+dc(c)+dc(a));return c}
function dc(a){a=String(a);return"0000000".slice(a.length)+a}function ec(){var a=G,b=H;b&2147483648?vb()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=v(bc(a,b)),a=b.next().value,b=b.next().value,a="-"+cc(a,b)):a=cc(a,b);return a}function bc(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function fc(a){return Array.prototype.slice.call(a)};var hc=typeof BigInt==="function"?BigInt.asIntN:void 0,ic=Number.isSafeInteger,jc=Number.isFinite,kc=Math.trunc,lc=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function mc(a){switch(typeof a){case "bigint":return!0;case "number":return jc(a);case "string":return lc.test(a);default:return!1}}function nc(a){if(!jc(a))throw ub("enum");return a|0}function oc(a){return a==null?a:jc(a)?a|0:void 0}function pc(a){if(typeof a!=="number")throw ub("int32");if(!jc(a))throw ub("int32");return a|0}
function tc(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return jc(a)?a|0:void 0}
function uc(a){var b=void 0;b!=null||(b=1024);if(!mc(a))throw ub("int64");var c=typeof a;switch(b){case 512:switch(c){case "string":return vc(a);case "bigint":return String(hc(64,a));default:return wc(a)}case 1024:switch(c){case "string":return b=kc(Number(a)),ic(b)?a=Tb(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a=vb()?Tb(hc(64,BigInt(a))):Tb(xc(a))),a;case "bigint":return Tb(hc(64,a));default:return ic(a)?Tb(yc(a)):Tb(wc(a))}case 0:switch(c){case "string":return vc(a);case "bigint":return Tb(hc(64,
a));default:return yc(a)}default:throw Error("Unknown format requested type for int64");}}
function xc(a){var b=a.length;if(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")return a;if(a.length<16)ac(Number(a));else if(vb())a=BigInt(a),G=Number(a&BigInt(4294967295))>>>0,H=Number(a>>BigInt(32)&BigInt(4294967295));else{b=+(a[0]==="-");H=G=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),H*=1E6,G=G*1E6+d,G>=4294967296&&(H+=Math.trunc(G/4294967296),H>>>=0,G>>>=0);b&&(b=v(bc(G,H)),a=b.next().value,b=b.next().value,G=a,H=b)}return ec()}
function yc(a){a=kc(a);if(!ic(a)){ac(a);var b=G,c=H;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);var d=c*4294967296+(b>>>0);b=Number.isSafeInteger(d)?d:cc(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}function wc(a){a=kc(a);ic(a)?a=String(a):(ac(a),a=ec());return a}function vc(a){var b=kc(Number(a));if(ic(b))return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return xc(a)}function I(a){return a==null||typeof a==="string"?a:void 0}
function zc(a,b,c,d){if(a!=null&&a[Bb]===Jb)return a;if(!Array.isArray(a))return c?d&2?((a=b[zb])||(a=new b,Hb(a.j),a=b[zb]=a),b=a):b=new b:b=void 0,b;c=a[C]|0;d=c|d&32|d&2;d!==c&&E(a,d);return new b(a)}function Ac(a,b,c){a=b?pc(a):tc(a);return a==null?c?0:void 0:a|0}function J(a,b,c){if(b){if(typeof a!=="string")throw Error();return a}var d;return(d=I(a))!=null?d:c?"":void 0};function Bc(a){return a};var Cc={},Dc=function(){try{var a=function(){return ea(Map,[],this.constructor)};u(a,Map);lb(new a);return!1}catch(b){return!0}}();function Ec(){this.g=new Map}p=Ec.prototype;p.get=function(a){return this.g.get(a)};p.set=function(a,b){this.g.set(a,b);this.size=this.g.size;return this};p.delete=function(a){a=this.g.delete(a);this.size=this.g.size;return a};p.clear=function(){this.g.clear();this.size=this.g.size};p.has=function(a){return this.g.has(a)};p.entries=function(){return this.g.entries()};
p.keys=function(){return this.g.keys()};p.values=function(){return this.g.values()};p.forEach=function(a,b){return this.g.forEach(a,b)};Ec.prototype[Symbol.iterator]=function(){return this.entries()};var K=function(){function a(){return ea(Map,[],this.constructor)}if(Dc)return Object.setPrototypeOf(Ec.prototype,Map.prototype),Object.defineProperties(Ec.prototype,{size:{value:0,configurable:!0,enumerable:!0,writable:!0}}),Ec;u(a,Map);return a}();function Fc(a){return a}
function L(a,b,c,d){c=c===void 0?Fc:c;d=d===void 0?Fc:d;var e=K.call(this)||this;e.L=a[C]|0;e.G=b;e.W=c;e.ea=e.G?Gc:d;for(var h=0;h<a.length;h++){var f=a[h],k=c(f[0],!1,!0),g=f[1];b?g===void 0&&(g=null):g=d(f[1],!1,!0,void 0,void 0,e.L);K.prototype.set.call(e,k,g)}return e}u(L,K);function Hc(a){if(a.L&2)throw Error("Cannot mutate an immutable Map");}function Ic(a,b){return Ib(Array.from(K.prototype.entries.call(a),b))}p=L.prototype;p.clear=function(){Hc(this);K.prototype.clear.call(this)};
p.delete=function(a){Hc(this);return K.prototype.delete.call(this,this.W(a,!0,!1))};p.entries=function(){if(this.G){var a=K.prototype.keys.call(this);a=new Lb(a,Jc,this)}else a=K.prototype.entries.call(this);return a};p.values=function(){if(this.G){var a=K.prototype.keys.call(this);a=new Lb(a,L.prototype.get,this)}else a=K.prototype.values.call(this);return a};p.forEach=function(a,b){this.G?K.prototype.forEach.call(this,function(c,d,e){a.call(b,e.get(d),d,e)}):K.prototype.forEach.call(this,a,b)};
p.set=function(a,b){Hc(this);a=this.W(a,!0,!1);return a==null?this:b==null?(K.prototype.delete.call(this,a),this):K.prototype.set.call(this,a,this.ea(b,!0,!0,this.G,!1,this.L))};p.has=function(a){return K.prototype.has.call(this,this.W(a,!1,!1))};p.get=function(a){a=this.W(a,!1,!1);var b=K.prototype.get.call(this,a);if(b!==void 0){var c=this.G;return c?(c=this.ea(b,!1,!0,c,this.la,this.L),c!==b&&K.prototype.set.call(this,a,c),c):b}};L.prototype[Symbol.iterator]=function(){return this.entries()};
L.prototype.toJSON=void 0;function Gc(a,b,c,d,e,h){a=zc(a,d,c,h);e&&(a=Kc(a));return a}function Jc(a){return[a,this.get(a)]}var Lc;function Mc(){return Lc||(Lc=new L(Hb([]),void 0,void 0,void 0,Cc))};function Nc(a,b,c,d){var e=d!==void 0;d=!!d;var h=[],f=a.length,k=4294967295,g=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=f&&a[f-1];n!=null&&typeof n==="object"&&n.constructor===Object?(f--,k=f):n=void 0;if(l&&!(b&128)&&!e){g=!0;var q;k=((q=Oc)!=null?q:Bc)(k-m,m,a,n,void 0)+m}}b=void 0;for(e=0;e<f;e++)if(q=a[e],q!=null&&(q=c(q,d))!=null)if(l&&e>=k){var t=e-m,y=void 0;((y=b)!=null?y:b={})[t]=q}else h[e]=q;if(n)for(var B in n)a=n[B],a!=null&&(a=c(a,d))!=null&&(f=+B,e=void 0,l&&!Number.isNaN(f)&&
(e=f+m)<k?h[e]=a:(f=void 0,((f=b)!=null?f:b={})[B]=a));b&&(g?h.push(b):h[k]=b);return h}function Pc(a){a[0]=Qc(a[0]);a[1]=Qc(a[1]);return a}function Qc(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Zb(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[C]|0;return a.length===0&&b&1?void 0:Nc(a,b,Qc)}if(a!=null&&a[Bb]===Jb)return Rc(a);if(a instanceof L)return a=a.size!==0?Ic(a,Pc):void 0,a;return}return a}var Oc;
function Rc(a){a=a.j;return Nc(a,a[C]|0,Qc)};function M(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[C]|0;if(db&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Sc();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var h=c.length;if(h){var f=h-1,k=c[f];if(k!=null&&typeof k==="object"&&k.constructor===Object){b=e&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var g in k)h=
+g,h<f&&(c[h+b]=k[g],delete k[g]);e=e&-16760833|(f&1023)<<14;break a}}if(b){g=Math.max(b,h-(e&128?0:-1));if(g>1024)throw Error("spvt");e=e&-16760833|(g&1023)<<14}}}E(a,e|64|d);return a}function Sc(){if(db)throw Error("carr");if(Ab!=null){var a;var b=(a=tb)!=null?a:tb={};a=b[Ab]||0;a>=5||(b[Ab]=a+1,b=Error(),ab(b,"incident"),bb(b))}};function Tc(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;return a.length===0&&c&1?void 0:Uc(a,c,b)}if(a!=null&&a[Bb]===Jb)return Vc(a);if(a instanceof L){b=a.L;if(b&2)return a;if(a.size){c=Hb(Ic(a));if(a.G)for(a=0;a<c.length;a++){var d=c[a],e=d[1];e==null||typeof e!=="object"?e=void 0:e!=null&&e[Bb]===Jb?e=Vc(e):Array.isArray(e)?e=Uc(e,e[C]|0,!!(b&32)):e=void 0;d[1]=e}return c}}}
function Uc(a,b,c){if(b&2)return a;!c||4096&b||16&b?a=Wc(a,b,!1,c&&!(b&16)):(Gb(a,34),b&4&&Object.freeze(a));return a}function Xc(a,b,c){a=new a.constructor(b);c&&(a.g=Kb);a.h=Kb;return a}function Vc(a){var b=a.j,c=b[C]|0;return F(a,c)?a:Yc(a,b,c)?Xc(a,b):Wc(b,c)}function Zc(a){var b=a.j,c=b[C]|0;return Yc(a,b,c)?Xc(a,b,!0):new a.constructor(Wc(b,c,!1))}function Wc(a,b,c,d){d!=null||(d=!!(34&b));a=Nc(a,b,Tc,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Kc(a){var b=a.j,c=b[C]|0;return F(a,c)?Yc(a,b,c)?Xc(a,b,!0):new a.constructor(Wc(b,c,!1)):a}function $c(a){if(a.g!==Kb)return!1;var b=a.j;b=Wc(b,b[C]|0);Gb(b,2048);a.j=b;a.g=void 0;a.h=void 0;return!0}function ad(a){if(!$c(a)&&F(a,a.j[C]|0))throw Error();}function bd(a,b){b===void 0&&(b=a[C]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Yc(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=Kb,!0):!1};function N(a,b){a=cd(a.j,b);if(a!==null)return a}function cd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),h=a.length-1;if(!(h<1+(c?0:-1))){if(e>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object){c=f[b];var k=!0}else if(e===h)c=f;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return k?f[b]=d:a[e]=d,d}return c}}function dd(a,b,c){ad(a);var d=a.j;O(d,d[C]|0,b,c);return a}
function O(a,b,c,d){var e=c+-1,h=a.length-1;if(h>=0&&e>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object)return f[c]=d,b}if(e<=h)return a[e]=d,b;if(d!==void 0){var k;h=((k=b)!=null?k:b=a[C]|0)>>14&1023||536870912;c>=h?d!=null&&(e={},a[h+-1]=(e[c]=d,e)):a[e]=d}return b}function ed(a,b,c){a=a.j;return fd(a,a[C]|0,b,c)!==void 0}
function gd(a,b,c,d,e){var h=a.j,f=h[C]|0;d=F(a,f)?1:d;e=!!e||d===3;d===2&&$c(a)&&(h=a.j,f=h[C]|0);a=hd(h,b);var k=a===Eb?7:a[C]|0,g=id(k,f);var l=4&g?!1:!0;if(l){4&g&&(a=fc(a),k=0,g=jd(g,f),f=O(h,f,b,a));for(var m=0,n=0;m<a.length;m++){var q=c(a[m]);q!=null&&(a[n++]=q)}n<m&&(a.length=n);c=(g|4)&-513;g=c&=-1025;g&=-4097}g!==k&&(E(a,g),2&g&&Object.freeze(a));return a=kd(a,g,h,f,b,d,l,e)}
function kd(a,b,c,d,e,h,f,k){var g=b;h===1||(h!==4?0:2&b||!(16&b)&&32&d)?ld(b)||(b|=!a.length||f&&!(4096&b)||32&d&&!(4096&b||16&b)?2:256,b!==g&&E(a,b),Object.freeze(a)):(h===2&&ld(b)&&(a=fc(a),g=0,b=jd(b,d),d=O(c,d,e,a)),ld(b)||(k||(b|=16),b!==g&&E(a,b)));2&b||!(4096&b||16&b)||bd(c,d);return a}function hd(a,b){a=cd(a,b);return Array.isArray(a)?a:Eb}function id(a,b){2&b&&(a|=2);return a|1}function ld(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function P(a,b,c,d,e){var h=a.j,f=h[C]|0;var k=F(a,f);a:{!k&&$c(a)&&(h=a.j,f=h[C]|0);var g=cd(h,b);a=!1;if(g==null){if(k){b=Mc();break a}g=[]}else if(g.constructor===L)if(g.L&2&&!k)g=Ic(g);else{b=g;break a}else Array.isArray(g)?a=!!((g[C]|0)&2):g=[];if(k){if(!g.length){b=Mc();break a}a||(a=!0,Hb(g))}else if(a){a=!1;Ib(g);g=fc(g);for(var l=0;l<g.length;l++){var m=g[l]=fc(g[l]);Array.isArray(m[1])&&(m[1]=Hb(m[1]))}g=Ib(g)}!a&&f&32&&Gb(g,32);d=new L(g,c,d,e);f=O(h,f,b,d);a||bd(h,f);b=d}!k&&c&&(b.la=
!0);return b}function fd(a,b,c,d){var e=!1;d=cd(a,d,void 0,function(h){var f=zc(h,c,!1,b);e=f!==h&&f!=null;return f});if(d!=null)return e&&!F(d)&&bd(a,b),d}function Q(a,b,c){var d=a.j,e=d[C]|0;b=fd(d,e,b,c);if(b==null)return b;e=d[C]|0;if(!F(a,e)){var h=Kc(b);h!==b&&($c(a)&&(d=a.j,e=d[C]|0),b=h,e=O(d,e,c,b),bd(d,e))}return b}function jd(a,b){return a=(2&b?a|2:a&-3)&-273}
function R(a,b){var c=c===void 0?!1:c;a=N(a,b);a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}function md(a,b){var c=c===void 0?0:c;var d;return(d=tc(N(a,b)))!=null?d:c}function S(a,b){var c=c===void 0?"":c;var d;return(d=I(N(a,b)))!=null?d:c}function nd(a,b,c){c=c===void 0?0:c;var d;return(d=oc(N(a,b)))!=null?d:c}
function od(a,b,c){if(c!=null&&typeof c!=="boolean")throw a=typeof c,Error("Expected boolean but got "+(a!="object"?a:c?Array.isArray(c)?"array":a:"null")+": "+c);return dd(a,b,c)}function T(a,b,c){dd(a,b,c==null?c:pc(c))}function U(a,b,c){if(c!=null&&typeof c!=="string")throw Error();return dd(a,b,c)}function pd(a,b,c){dd(a,b,c==null?c:nc(c))};function V(a,b,c){this.j=M(a,b,c,2048)}V.prototype.toJSON=function(){return Rc(this)};function qd(a){return JSON.stringify(Rc(a))}V.prototype[Bb]=Jb;V.prototype.toString=function(){return this.j.toString()};function rd(a){this.j=M(a,void 0,void 0,2048)}u(rd,V);function sd(a){this.j=M(a,void 0,void 0,2048)}u(sd,V);function td(a){this.j=M(a,void 0,void 0,2048)}u(td,V);function ud(a){this.j=M(a,void 0,void 0,2048)}u(ud,V);function vd(a){this.j=M(a,void 0,void 0,2048)}u(vd,V);function wd(a){this.j=M(a,void 0,void 0,2048)}u(wd,V);wd.prototype.M=function(){return S(this,3)};wd.prototype.da=function(a){od(this,5,a)};function W(a){this.j=M(a,void 0,void 0,2048)}u(W,V);W.prototype.M=function(){return S(this,1)};W.prototype.da=function(a){od(this,2,a)};function xd(a){this.j=M(a,void 0,void 0,2048)}u(xd,V);function yd(a){this.j=M(a,void 0,void 0,2048)}u(yd,V);function zd(a){this.j=M(a,void 0,void 0,2048)}u(zd,V);
function Ad(a){var b=a.j,c=b;b=b[C]|0;var d=void 0===Mb?2:4,e=F(a,b),h=e?1:d;d=h===3;var f=!e;(h===2||f)&&$c(a)&&(c=a.j,b=c[C]|0);a=hd(c,7);var k=a===Eb?7:a[C]|0,g=id(k,b);if(e=!(4&g)){var l=a,m=b,n=!!(2&g);n&&(m|=2);for(var q=!n,t=!0,y=0,B=0;y<l.length;y++){var D=zc(l[y],wd,!1,m);if(D instanceof wd){if(!n){var pa=F(D);q&&(q=!pa);t&&(t=pa)}l[B++]=D}}B<y&&(l.length=B);g|=4;g=t?g&-4097:g|4096;g=q?g|8:g&-9}g!==k&&(E(a,g),2&g&&Object.freeze(a));if(f&&!(8&g||!a.length&&(h===1||(h!==4?0:2&g||!(16&g)&&32&
b)))){ld(g)&&(a=fc(a),g=jd(g,b),b=O(c,b,7,a));f=a;k=g;for(l=0;l<f.length;l++)g=f[l],m=Kc(g),g!==m&&(f[l]=m);k|=8;g=k=f.length?k|4096:k&-4097;E(a,g)}return a=kd(a,g,c,b,7,h,e,d)};function Bd(a){this.j=M(a,void 0,void 0,2048)}u(Bd,V);function Cd(a){this.j=M(a,void 0,void 0,2048)}u(Cd,V);function Dd(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};function Ed(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function Fd(a){a=a===void 0?document:a;return a.createElement("img")};var Gd=[];function Hd(){var a=Gd;Gd=[];a=v(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;try{b()}catch(c){}}}function Id(a){Gd.push(a);Gd.length===1&&(window.Promise?Promise.resolve().then(Hd):(a=window.setImmediate,Rb(a)?a(Hd):setTimeout(Hd,0)))};function Jd(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};var Kd={capture:!0},Ld={passive:!0},Md=Ed(function(){var a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});z.addEventListener("test",null,b)}catch(c){}return a});function Nd(a){return a?a.passive&&Md()?a:a.capture||!1:!1}function Od(a,b,c,d){typeof a.addEventListener==="function"&&a.addEventListener(b,c,Nd(d))}function Pd(a){var b=X;b.readyState==="complete"||b.readyState==="interactive"?Id(a):b.addEventListener("DOMContentLoaded",a)}
function Wd(a){var b=window;b.document.readyState==="complete"?Id(a):b.addEventListener("load",a)};function Xd(a,b,c,d){Yd(a,b,c===void 0?null:c,d===void 0?!1:d)}
function Yd(a,b,c,d){var e=!1;e=e===void 0?!1:e;a.google_image_requests||(a.google_image_requests=[]);var h=Fd(a.document);if(c||d){var f=function(k){c&&c(k);if(d){k=a.google_image_requests;var g=Ya(k,h);g>=0&&Array.prototype.splice.call(k,g,1)}typeof h.removeEventListener==="function"&&h.removeEventListener("load",f,Nd());typeof h.removeEventListener==="function"&&h.removeEventListener("error",f,Nd())};Od(h,"load",f);Od(h,"error",f)}e&&(h.attributionSrc="");h.src=b;a.google_image_requests.push(h)}
function Zd(a){var b=window;var c=c===void 0?!1:c;var d;if(d=b.navigator)d=b.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&typeof b.navigator.sendBeacon==="function"?b.navigator.sendBeacon(a):Xd(b,a,void 0,c)};var $d=0;function ae(){var a=be($d,document.currentScript);a&&(a.dataset.initialized="true")}function ce(a){return(a=be(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function be(a,b){return(b=b===void 0?null:b)&&b.getAttribute("data-jc")===String(a)?b:document.querySelector('[data-jc="'+a+'"]')}
function de(a){var b=b===void 0?.01:b;if(!(Math.random()>b)){var c=be(a,document.currentScript);a="https://"+(c&&c.getAttribute("data-jc-rcd")==="true"?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com")+"/pagead/gen_204?id=jca&jc="+a+"&version="+ce(a)+"&sample="+b;Zd(a)}};function ee(a,b){var c=c===void 0?{}:c;this.error=a;this.meta=c;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror"};function fe(a){var b=a.toString();a.name&&b.indexOf(a.name)==-1&&(b+=": "+a.name);a.message&&b.indexOf(a.message)==-1&&(b+=": "+a.message);if(a.stack)a:{a=a.stack;var c=b;try{a.indexOf(c)==-1&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");b=a.replace(RegExp("\n *","g"),"\n");break a}catch(e){b=c;break a}b=void 0}return b};var ge=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");function he(a,b){this.g=a;this.h=b}function ie(a,b){this.url=a;this.g=!!b;this.depth=null};var je=null;function ke(){var a=a===void 0?z:a;return(a=a.performance)&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function le(){var a=a===void 0?z:a;return(a=a.performance)&&a.now?a.now():null};function me(a,b){var c=le()||ke();this.label=a;this.type=b;this.value=c;this.duration=0;this.taskId=this.slotId=void 0;this.uniqueId=Math.random()};var Y=z.performance,ne=!!(Y&&Y.mark&&Y.measure&&Y.clearMarks),oe=Ed(function(){var a;if(a=ne){var b=b===void 0?window:b;if(je===null){je="";try{a="";try{a=b.top.location.hash}catch(d){a=b.location.hash}if(a){var c=a.match(/\bdeid=([\d,]+)/);je=c?c[1]:""}}catch(d){}}b=je;a=!!b.indexOf&&b.indexOf("1337")>=0}return a});
function pe(){var a=window;this.h=[];this.i=a||z;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=oe()||(b!=null?b:Math.random()<1)}function qe(a){a&&Y&&oe()&&(Y.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),Y.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}pe.prototype.start=function(a,b){if(!this.g)return null;a=new me(a,b);b="goog_"+a.label+"_"+a.uniqueId+"_start";Y&&oe()&&Y.mark(b);return a};
pe.prototype.end=function(a){if(this.g&&Ob(a.value)){a.duration=(le()||ke())-a.value;var b="goog_"+a.label+"_"+a.uniqueId+"_end";Y&&oe()&&Y.mark(b);!this.g||this.h.length>2048||this.h.push(a)}};function re(){this.i="&";this.h={};this.l=0;this.g=[]}function se(a,b){var c={};c[a]=b;return[c]}function te(a,b,c,d,e){var h=[];Dd(a,function(f,k){(f=ue(f,b,c,d,e))&&h.push(k+"="+f)});return h.join(b)}
function ue(a,b,c,d,e){if(a==null)return"";b=b||"&";c=c||",$";typeof c==="string"&&(c=c.split(""));if(a instanceof Array){if(d||(d=0),d<c.length){for(var h=[],f=0;f<a.length;f++)h.push(ue(a[f],b,c,d+1,e));return h.join(c[d])}}else if(typeof a==="object")return e||(e=0),e<2?encodeURIComponent(te(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}
function ve(a,b,c){b="https://"+b+c;var d=we(a)-c.length;if(d<0)return"";a.g.sort(function(m,n){return m-n});c=null;for(var e="",h=0;h<a.g.length;h++)for(var f=a.g[h],k=a.h[f],g=0;g<k.length;g++){if(!d){c=c==null?f:c;break}var l=te(k[g],a.i,",$");if(l){l=e+l;if(d>=l.length){d-=l.length;b+=l;e=a.i;break}c=c==null?f:c}}a="";c!=null&&(a=e+"trn="+c);return b+a}function we(a){var b=1,c;for(c in a.h)c.length>b&&(b=c.length);return 3997-b-a.i.length-1};var xe=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function ye(a,b){if(!b)return a;var c=a.indexOf("#");c<0&&(c=a.length);var d=a.indexOf("?");if(d<0||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}
function ze(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)ze(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+encodeURIComponent(String(b))))}function Ae(a,b,c,d){for(var e=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var h=a.charCodeAt(b-1);if(h==38||h==63)if(h=a.charCodeAt(b+e),!h||h==61||h==38||h==35)return b;b+=e+1}return-1}var Be=/#|$/,Ce=/[?&]($|#)/;
function De(a,b){for(var c=a.search(Be),d=0,e,h=[];(e=Ae(a,d,b,c))>=0;)h.push(a.substring(d,e)),d=Math.min(a.indexOf("&",e)+1||c,c);h.push(a.slice(d));return h.join("").replace(Ce,"$1")}function Ee(a,b){a=De(a,"label");b=b!=null?"="+encodeURIComponent(String(b)):"";return ye(a,"label"+b)};function Fe(){var a=Ge;this.pinger=He;this.g=a===void 0?null:a;this.h=null;this.i=!1;this.m=this.l}function Ie(a,b){var c=Je;try{if(c.g&&c.g.g){var d=c.g.start(a.toString(),3);var e=b();c.g.end(d)}else e=b()}catch(k){b=!0;try{qe(d),b=c.m(a,new ee(k,{message:fe(k)}),void 0,void 0)}catch(g){c.l(217,g)}if(b){var h,f;(h=window.console)==null||(f=h.error)==null||f.call(h,k)}else throw k;}return e}
function Ke(a,b){return function(){var c=za.apply(0,arguments);return Ie(a,function(){return b.apply(void 0,c)})}}
Fe.prototype.l=function(a,b,c,d,e){e=e||"jserror";var h=void 0;try{var f=new re;f.g.push(1);f.h[1]=se("context",a);b.error&&b.meta&&b.id||(b=new ee(b,{message:fe(b)}));if(b.msg){var k=b.msg.substring(0,512);f.g.push(2);f.h[2]=se("msg",k)}var g=b.meta||{};if(this.h)try{this.h(g)}catch(ra){}if(d)try{d(g)}catch(ra){}d=[g];f.g.push(3);f.h[3]=d;var l;if(!(l=D)){k=z;d=[];g=null;do{var m=k;try{var n;if(n=!!m&&m.location.href!=null)b:{try{lb(m.foo);n=!0;break b}catch(ra){}n=!1}var q=n}catch(ra){q=!1}if(q){var t=
m.location.href;g=m.document&&m.document.referrer||null}else t=g,g=null;d.push(new ie(t||""));try{k=m.parent}catch(ra){k=null}}while(k&&m!==k);t=0;for(var y=d.length-1;t<=y;++t)d[t].depth=y-t;m=z;if(m.location&&m.location.ancestorOrigins&&m.location.ancestorOrigins.length===d.length-1)for(y=1;y<d.length;++y){var B=d[y];B.url||(B.url=m.location.ancestorOrigins[y-1]||"",B.g=!0)}l=d}var D=l;var pa=new ie(z.location.href,!1);l=null;var qc=D.length-1;for(m=qc;m>=0;--m){var Z=D[m];!l&&ge.test(Z.url)&&(l=
Z);if(Z.url&&!Z.g){pa=Z;break}}Z=null;var uf=D.length&&D[qc].url;pa.depth!==0&&uf&&(Z=D[qc]);h=new he(pa,Z);if(h.h){var vf=h.h.url||"";f.g.push(4);f.h[4]=se("top",vf)}var rc={url:h.g.url||""};if(h.g.url){var sc=h.g.url.match(xe),Qd=sc[1],Rd=sc[3],Sd=sc[4];D="";Qd&&(D+=Qd+":");Rd&&(D+="//",D+=Rd,Sd&&(D+=":"+Sd));var Td=D}else Td="";rc=[rc,{url:Td}];f.g.push(5);f.h[5]=rc;Le(this.pinger,e,f,this.i,c)}catch(ra){try{var Ud,Vd;Le(this.pinger,e,{context:"ecmserr",rctx:a,msg:fe(ra),url:(Vd=(Ud=h)==null?void 0:
Ud.g.url)!=null?Vd:""},this.i,c)}catch(Xf){}}return!0};function Me(){};function Ne(){this.domain="pagead2.googlesyndication.com";this.path="/pagead/gen_204?id=";this.g=Math.random()}function Oe(){var a=He,b=window.google_srt;b>=0&&b<=1&&(a.g=b)}function Le(a,b,c,d,e){if(((d===void 0?0:d)?a.g:Math.random())<(e||.01))try{if(c instanceof re)var h=c;else h=new re,Dd(c,function(k,g){var l=h,m=l.l++;k=se(g,k);l.g.push(m);l.h[m]=k});var f=ve(h,a.domain,a.path+b+"&");f&&Xd(z,f)}catch(k){}};var Pe=[Na,Oa,Qa,Pa,Ma,Sa,Ta,Ra,Ua];function Qe(a,b){if(a instanceof Ja)return a;var c=Pe;c=c===void 0?Va:c;a:if(c=c===void 0?Va:c,a instanceof Ja)c=a;else{for(var d=0;d<c.length;++d){var e=c[d];if(e instanceof La&&e.na(a)){c=new Ja(a);break a}}c=void 0}c=c||Ka;c===Ka&&b(a);return c}
function Re(a){return function(b){b={id:"unsafeurl",ctx:a,url:b};var c=[];for(d in b)ze(d,b[d],c);var d=ye("https://pagead2.googlesyndication.com/pagead/gen_204",c.join("&"));navigator.sendBeacon&&navigator.sendBeacon(d,"")}};var He,Je,Ge=new pe;function Se(){if(!window.google_measure_js_timing){var a=Ge;a.g=!1;a.h!==a.i.google_js_reporting_queue&&(oe()&&Za(a.h,qe),a.h.length=0)}}(function(a){He=a!=null?a:new Ne;typeof window.google_srt!=="number"&&(window.google_srt=Math.random());Oe();Je=new Fe;Je.h=function(b){var c=$d;c!==0&&(b.jc=String(c),b.shv=ce(c))};Je.i=!0;window.document.readyState==="complete"?Se():Ge.g&&Od(window,"load",function(){Se()})})();function Te(a,b){return Ke(a,b)}
function Ue(a,b){var c="ba";Me.ba&&Me.hasOwnProperty(c)||(c=new Me,Me.ba=c);c=[];!b.eid&&c.length&&(b.eid=c.toString());Le(He,a,b,!0)};function Ve(){var a=a===void 0?z:a;return a.oneAfmaInstance};var X=document,We=window;function Xe(a){var b=X;try{return b.querySelectorAll("*["+a+"]")}catch(c){return[]}};Jd({za:0,ya:1,va:2,qa:3,wa:4,ra:5,xa:6,ta:7,ua:8,pa:9,sa:10,Aa:11}).map(function(a){return Number(a)});Jd({Ca:0,Da:1,Ba:2}).map(function(a){return Number(a)});function Ye(a){this.j=M(a,void 0,void 0,2048)}u(Ye,V);function Ze(a){var b=new Ye;ad(b);b=gd(b,1,oc,2,!0);if(Array.isArray(a))for(var c=a.length,d=0;d<c;d++)b.push(nc(a[d]));else for(a=v(a),c=a.next();!c.done;c=a.next())b.push(nc(c.value))};[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});Ze([1,8,9,10,11,12,2,3,4,5,15,16,19,20,21,23]);Ze([1,6,7,9,10,11,12,2,22,3,4,5,13,14,18,19,20,21,23]);Ze([1,6,7,9,10,11,12,22,2,3,4,5,13,14,17,18,19,20,21,23]);new Ye;function $e(a){this.j=M(a,void 0,void 0,2048)}u($e,V);function af(a,b){b=S(a,2)||b;if(!b)return"";if(R(a,13))return b;var c=/[?&]adurl=([^&]+)/.exec(b);if(!c)return b;var d=[b.slice(0,c.index+1)];P(a,4,void 0,J,J).forEach(function(e,h){d.push(encodeURIComponent(h)+"="+encodeURIComponent(e)+"&")});d.push(b.slice(c.index+1));return R(a,27)?(b=d.join(""),(a=P(a,4,void 0,J,J).get("label"))&&(b=Ee(b,a)),b):d.join("")}
function bf(a,b){b=b===void 0?[]:b;b=b.length>0?b:Xe("data-asoch-targets");a=P(a,1,zd,J);for(var c=[],d=0;d<b.length;++d){for(var e=b[d].getAttribute("data-asoch-targets"),h=e.split(","),f=!0,k=v(h),g=k.next();!g.done;g=k.next())if(!a.has(g.value)){f=!1;break}if(f){f=a.get(h[0]);for(e=1;e<h.length;++e){k=a.get(h[e]);f=Zc(f);f=Rc(f);k=Rc(k);g=Math.max(f.length,k.length);for(var l=0;l<g;++l)f[l]==null&&(f[l]=k[l]);f=new zd(f)}h=P(f,4,void 0,J,J);oc(N(f,5))!=null&&h.set("nb",nd(f,5).toString());c.push({element:b[d],
data:f})}else Ue("gdn-asoch",{type:1,data:e})}return c}function cf(a,b,c,d){c=af(b,c);if(c.length!==0){if(d===609&&ed(b,rd,24)){var e=Q(b,rd,24);a.setAttribute("attributionDestination",S(e,2));a.setAttribute("attributionSourceNonce",S(e,1))}(e=(e=be(35))&&e.dataset.expanded?e.dataset.expanded:null)&&d===557&&(c=df(c,"expanded",e));Xa(a,Qe(c,Re(d)));a.target||(a.target=I(N(b,11))!=null?S(b,11):"_top")}}
function ef(a){var b=b===void 0?"":b;var c=c===void 0?!1:c;a=v(a);for(var d=a.next();!d.done;d=a.next()){var e=d.value;d=e.data;var h=b.length===0?!1:e.element.matches(b);e.element.tagName!="A"||R(d,1)||h||(e=e.element,cf(e,d,e.href,c?1087:609))}}function df(a,b,c){b=encodeURIComponent(b);var d=encodeURIComponent(c);c=new RegExp("[?&]"+b+"=([^&]+)");var e=c.exec(a);b=b+"="+d;return e?a.replace(c,e[0].charAt(0)+b):a.replace("?","?"+b+"&")}
function ff(a){var b=Ve();if(b){var c=v(a);for(a=c.next();!a.done;a=c.next()){var d=a.value.data;if(d&&ed(d,xd,8)&&(a=Q(d,xd,8),a=S(a,4))){c=b.fetchAppStoreOverlay;d=Q(d,xd,8);d=S(d,6);c.call(b,a,void 0,d);break}}}}
function gf(a,b){function c(k,g){if(g){k=v(e);for(var l=k.next();!l.done;l=k.next())l=l.value,g[l.M()]&&l.da(!0)}}b=b===void 0?500:b;var d=[],e=[];a=v(a);for(var h=a.next();!h.done;h=a.next())(h=h.value.data)&&ed(h,W,12)&&(e.push(Q(h,W,12)),d.push(Q(h,W,12).M()));a=Ve();d=v(d);for(h=d.next();!h.done;h=d.next()){h=h.value;var f=void 0;(f=a)==null||f.canOpenAndroidApp(h,c,function(){},b)}}
function hf(a,b,c,d){function e(B){return d.openStoreOverlay(B,l,m,S(h,6))}if(!b||!ed(b,xd,8))return!1;var h=Q(b,xd,8),f=S(h,2);P(b,10,void 0,J,J).forEach(function(B,D){f=df(f,D,B)});jf(b)&&R(b,15)&&!/[?&]label=/.test(c)&&(c=kf(c,"label","deep_link_fallback"));if(a==null?0:R(a,1))S(b,9)?Ue("skspvc",{url:1}):Ue("skspvc",{url:0});var k=a==null?void 0:R(a,7),g=S(b,9),l=void 0,m=void 0,n=-1;if(k&&g){var q=Ee(g,"skspvc_triggered"),t=Ee(g,"skspvc_registered"),y=Ee(g,"skspvc_dismissed");l=function(){Zd(q);
n=setTimeout(function(){Zd(t)},3E3)};m=function(){Zd(y);clearTimeout(n)}}return d.redirectForStoreU2({clickUrl:c,trackingUrl:S(h,3),finalUrl:f,pingFunc:R(b,13)?d.httpTrack:d.click,openFunc:(a==null?0:R(a,1))?e:d.openIntentOrNativeApp,isExternalClickUrl:R(b,13)})}function lf(a,b,c,d){c&&c.startsWith("intent:")?d.openIntentOrNativeApp(c):a?b?d.openBrowser(c):d.openChromeCustomTab(c):d.openSystemBrowser(c,{useFirstPackage:!0,useRunningProcess:!0})}
function mf(a,b){b=b===void 0?null:b;if(b===null){b=new Fa({url:a,oa:null});if(b.g.dsh==="1"||b.g.aspm!=="1"){var c=Ga(b,0);a=c?navigator.sendBeacon?navigator.sendBeacon(c.T,"")?c.V:Ia(b,2):Ia(b,0):a}else if(b=Ga(b,1))fetch(b.T,{keepalive:!0,mode:"no-cors",credentials:"include"}),a=b.V;return a}c=Ga(new Fa({url:a}),0);if(!c)return a;b(c.T);return c.V}function nf(a,b){(b===void 0||b)&&We.fetch?We.fetch(a,{method:"GET",keepalive:!0,mode:"no-cors"}).then(function(c){c.ok||Xd(We,a)}):Xd(We,a)}
function kf(a,b,c){b=encodeURIComponent(String(b));c=encodeURIComponent(String(c));return a.replace("?","?"+b+"="+c+"&")}function jf(a){a=v(Ad(a));for(var b=a.next();!b.done;b=a.next())if(b=b.value,nd(b,1)===3&&S(b,2))return!0;return!1};function of(a,b){return a&&(a=a.match(b+"=([^&]+)"))&&a.length==2?a[1]:""};function pf(a){this.j=M(a,void 0,void 0,2048)}u(pf,V);function qf(a){this.j=M(a,void 0,void 0,2048)}u(qf,V);function rf(a,b){return U(a,2,b)}function sf(a,b){return U(a,3,b)}function tf(a,b){return U(a,4,b)}function wf(a,b){return U(a,5,b)}function xf(a,b){return U(a,9,b)}
function yf(a,b){ad(a);var c=a.j,d=c[C]|0;if(b==null)O(c,d,10);else{for(var e=b===Eb?7:b[C]|0,h=e,f=ld(e),k=f||Object.isFrozen(b),g=!0,l=!0,m=0;m<b.length;m++){var n=b[m];f||(n=F(n),g&&(g=!n),l&&(l=n))}f||(e=g?13:5,e=l?e&-4097:e|4096);k&&e===h||(b=fc(b),h=0,e=jd(e,d));e!==h&&E(b,e);d=O(c,d,10,b);2&e||!(4096&e||16&e)||bd(c,d)}return a}function zf(a,b){return od(a,11,b)}function Af(a,b){return U(a,1,b)}function Bf(a,b){return od(a,7,b)};var Cf="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function Df(a){var b;return(b=a.google_tag_data)!=null?b:a.google_tag_data={}}function Ef(a){var b,c;return typeof((b=a.navigator)==null?void 0:(c=b.userAgentData)==null?void 0:c.getHighEntropyValues)==="function"}
function Ff(){var a=window;if(!Ef(a))return null;var b=Df(a);if(b.uach_promise)return b.uach_promise;a=a.navigator.userAgentData.getHighEntropyValues(Cf).then(function(c){b.uach!=null||(b.uach=c);return c});return b.uach_promise=a}
function Gf(a){var b;return zf(yf(wf(rf(Af(tf(Bf(xf(sf(new qf,a.architecture||""),a.bitness||""),a.mobile||!1),a.model||""),a.platform||""),a.platformVersion||""),a.uaFullVersion||""),((b=a.fullVersionList)==null?void 0:b.map(function(c){var d=new pf;d=U(d,1,c.brand);return U(d,2,c.version)}))||[]),a.wow64||!1)}function Hf(){var a,b;return(b=(a=Ff())==null?void 0:a.then(function(c){return Gf(c)}))!=null?b:null};function If(a){var b=this;this.v=pb||nb||qb||ob;var c=Xe("data-asoch-meta");if(c.length!==1)Ue("gdn-asoch",{type:2,data:c.length});else{this.O=70;this.h=new Bd(JSON.parse(c[0].getAttribute("data-asoch-meta"))||[]);this.J=a["extra-meta"]?new Bd(JSON.parse(a["extra-meta"])):null;this.N=a["is-fsn"]==="true";this.ga=a["is-tap-disabled-for-fsn"]==="true";this.m=a["ios-store-overlay-config"]?new vd(JSON.parse(a["ios-store-overlay-config"])):null;this.ia=a["use-cct-over-browser"]==="true";this.Y=a["correct-redirect-url-for-och-15-click"]===
"true";this.ha=a["spitzer-use-click-url-for-fallback"]==="true";this.D=a["default-msg-in-och"]==="true";this.fa=a["enable-paw"]==="true";this.H=a["allow-redirection-muted-in-och"]==="true";this.I=Number(a["custom-async-tracking-throttle-interval"])||-1;this.o="";c=Hf();c!=null&&c.then(function(e){var h=qd(e);e=[];for(var f=0,k=0;k<h.length;k++){var g=h.charCodeAt(k);g>255&&(e[f++]=g&255,g>>=8);e[f++]=g}h=3;h===void 0&&(h=0);if(!sb)for(sb={},f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),
k=["+/=","+/","-_=","-_.","-_"],g=0;g<5;g++){var l=f.concat(k[g].split(""));rb[g]=l;for(var m=0;m<l.length;m++){var n=l[m];sb[n]===void 0&&(sb[n]=m)}}h=rb[h];f=Array(Math.floor(e.length/3));k=h[64]||"";for(g=l=0;l<e.length-2;l+=3){var q=e[l],t=e[l+1];n=e[l+2];m=h[q>>2];q=h[(q&3)<<4|t>>4];t=h[(t&15)<<2|n>>6];n=h[n&63];f[g++]=m+q+t+n}m=0;n=k;switch(e.length-l){case 2:m=e[l+1],n=h[(m&15)<<2]||k;case 1:e=e[l],f[g]=h[e>>2]+h[(e&3)<<4|m>>4]+n+k}b.o=f.join("")});this.g=bf(this.h);this.D&&(this.l=null,P(this.h,
1,zd,J).forEach(function(e){b.l!=null||I(N(e,2))==null||I(N(e,9))==null||R(e,13)||(b.l=e)}));this.ka=Number(a["deeplink-and-android-app-validation-timeout"])||500;this.P=-Infinity;this.u=this.K=0;this.i=S(this.h,5)||"";this.X=R(this.h,11);this.J&&(this.X=R(this.J,11));this.A=this.Z=this.R=this.S=this.C=null;R(this.h,3)||(ef(this.g),od(this.h,3,!0));Jf(this.g);a=Ve();!this.v&&a&&gf(this.g,this.ka);var d;if(a&&((d=this.m)==null?0:R(d,2)))switch(d=function(){var e=md(b.m,4);e>0?z.setTimeout(function(){ff(b.g)},
e):ff(b.g)},nd(this.m,3)){case 1:a.runOnOnShowEvent(d);break;case 2:Wd(d);break;default:ff(this.g)}Od(X,"click",Te(557,function(e){Kf(b,e)}),Kd);Od(X,"auxclick",Te(557,function(e){e.button===1&&Kf(b,e)}),Kd);this.i&&typeof window.ss==="function"&&Od(X.body,"mouseover",Te(626,function(){window.ss(b.i,0)}),Ld);typeof window.ivti==="function"&&window.ivti(X.body);d=window;d.googqscp&&typeof d.googqscp.registerCallback==="function"&&d.googqscp.registerCallback(function(e,h,f,k,g){b.C=e;b.A=h;b.S=f;b.R=
k;b.Z=g});ae()}}
function Kf(a,b){if(!b.defaultPrevented||a.C===b){for(var c,d,e=b.target;(!c||!d)&&e;){d||e.tagName!="A"||(d=e);var h=e.hasAttribute("data-asoch-targets"),f=e.hasAttribute("data-asoch-fixed-value");if(!c)if(f)c=new zd(JSON.parse(e.getAttribute("data-asoch-fixed-value"))||[]);else if(e.tagName=="A"||h)if(h=h&&e.getAttribute("data-asoch-is-dynamic")==="true"?bf(a.h,[e]):a.g,h=Lf(h,e))c=h.data;e=e.parentElement}e=c&&!R(c,1);if(a.D&&a.l&&b.defaultPrevented)Mf(a,b,d,e?c:a.l);else{if(e){if(!a.D&&b.defaultPrevented){Mf(a,
b,d,c);return}h=v(gd(c,6,I,void 0===Mb?2:4));for(f=h.next();!f.done;f=h.next())nf(f.value)}a.H&&e&&R(c,21)&&(b.preventDefault?b.preventDefault():b.returnValue=!1);if(d&&e){c=e?c:null;(e=Lf(a.g,d))?e=e.data:(e=new zd,U(e,2,d.href),U(e,11,d.target||"_top"),a.g.push({element:d,data:e}));cf(d,c||e,S(e,2),557);Nf(a,b,d,c);e=v(gd(a.h,17,I,void 0===Mb?2:4));for(f=e.next();!f.done;f=e.next()){h=void 0;var k=f.value,g=X.body;h=h===void 0?{}:h;typeof window.CustomEvent==="function"?f=new CustomEvent(k,h):(f=
document.createEvent("CustomEvent"),f.initCustomEvent(k,!!h.bubbles,!!h.cancelable,h.detail));g.dispatchEvent(f)}var l;if(c==null?0:(l=Q(c,yd,26))==null?0:I(N(l,1))!=null){l=new sd;oc(N(c,5))!=null?(e=nd(c,5),pd(l,1,e)):(e=of(d.href,"nb"),e!=""&&pd(l,1,+e));e=of(d.href,"nx");e!=""&&T(l,2,+e);e=of(d.href,"ny");e!=""&&T(l,3,+e);e=of(d.href,"bg");e!=""&&U(l,4,e);e=of(d.href,"nm");e!=""&&T(l,5,+e);e=of(d.href,"mb");e!=""&&T(l,6,+e);e=De(d.href,"bg");Xa(d,Qe(e,Re(1211)));e=Q(c,yd,26);f=S(e,1);e=Q(c,yd,
26);e=S(e,2);h=tc(N(c,20))!=null?md(c,20):null;g=qd(l);l=a.o;k=z;k=k===void 0?window:k;var m=new Cd;f=U(m,1,f);f=U(f,4,g);f=U(f,10,Date.now().toString());h!==null&&T(f,2,h);l!==null&&U(f,3,l);pd(f,9,7);var n;k==null||(n=k.fence)==null||n.setReportEventDataForAutomaticBeacons({eventType:"reserved.top_navigation_start",eventData:JSON.stringify(f),destination:["buyer"],once:!0});var q;k==null||(q=k.fence)==null||q.reportEvent({eventType:"click",eventData:e,destination:["component-seller"]})}R(a.h,16)||
a.N?Of(a,b,d,c):(n="",(q=Ve())&&(n=q.appendClickSignals(d.href)),Pf(a,b,d,c,n))}}}}
function Mf(a,b,c,d){if(a.C===b&&a.A){var e=new ud(a.A),h=S(d,9),f="";switch(nd(e,4,1)){case 2:if(md(e,2))f="blocked_fast_click";else if(S(e,1)||S(e,7))f="blocked_border_click";break;case 3:var k=k===void 0?X:k;f=k.getElementById?k.getElementById("common_15click_anchor"):null;k=window;if(typeof k.copfcChm==="function"&&f){var g=Zc(d);pd(g,5,12);P(g,4,void 0,J,J).set("nb",(12).toString());var l=Lf(a.g,f);l?l.data=g:a.g.push({element:f,data:g});!a.Y&&c&&(Nf(a,b,c,g),U(g,2,c.href));k.copfcChm(b,af(g,
f.href),null,ed(e,td,10)?qd(Q(e,td,10)):null);a.Y&&Nf(a,b,f,g)}f="onepointfiveclick_first_click"}if(h&&f){c=h+"&label="+f;if(f==="onepointfiveclick_first_click"){k=a.S;f=a.R;h=a.Z;e=new $e;d=nd(d,5);g=b.clientX;dd(e,1,g==null?g:uc(g));g=b.clientY;dd(e,2,g==null?g:uc(g));T(e,3,d);d=k?k.changedTouches:[];f=f?f.changedTouches:[];d&&f&&d.length>0&&f.length>0&&(T(e,4,d[0].clientX),T(e,5,d[0].clientY),T(e,6,f[0].clientX),T(e,7,f[0].clientY));(b.isTrusted===!1||navigator.userActivation&&navigator.userActivation.hasBeenActive===
!1||navigator.userActivation&&navigator.userActivation.isActive===!1)&&od(e,8,!0);if(h!=null)for(b=v(Object.entries(h)),d=b.next();!d.done;d=b.next())h=v(d.value),d=h.next().value,h=h.next().value,d=Number(d),h=Date.now()-Number(h),P(e,9,void 0,Ac,Ac).set(d,h);c+="&cpspb="+qd(e)}nf(c,!1)}de(a.O)}}
function Of(a,b,c,d){var e,h,f;ya(new xa(new ta(function(k){switch(k.g){case 1:e="";h=Ve();if(!h){k.F(2);break}b.preventDefault();return k.v(h.appendClickSignalsAsync(c.href),3);case 3:e=k.o||"";if(!a.N){k.F(2);break}return a.ga?k.return():k.v(h.getNativeClickMeta(),5);case 5:if(f=k.o){if(f.customClickGestureEligible)return k.return();e=kf(e,"nas",f.encodedNas)}case 2:Pf(a,b,c,d,e),k.D()}})))}
function Pf(a,b,c,d,e){a.K++;a.u<0&&(a.u=Date.now());var h=R(a.h,2),f=a.I>0?a.I:300;f=h&&Date.now()-a.P>f;var k=Ve();if(k){b.preventDefault?b.preventDefault():b.returnValue=!1;c=R(d,13)?e:k.logScionEventAndAddParam(e);if(!a.v&&d&&ed(d,W,12)){b=Q(d,W,12).M();e="";if(Ad(d).length>0)for(var g=v(Ad(d)),l=g.next();!l.done;l=g.next())l=l.value,e+=S(l,2)+" "+l.M()+" ";e=Q(d,W,12);R(e,2)?(k.click(c),k.openAndroidApp(b),b=!0):b=!1}else b=!1;if(!b&&!hf(a.m,d,c,k))a:{b=a.ia;e=a.v;g=a.H;l=a.ha;g=g===void 0?!1:
g;l=l===void 0?!1:l;var m=R(d,15);if(!l&&m&&I(N(d,22))!=null)lf(b,e,S(d,22),k);else{var n=Ga(new Fa({url:c}),0);l=m&&(n&&n.version===3||l);if(h&&f&&!l&&(c=mf(c,k.click),g&&(d==null?0:R(d,21))))break a;lf(b,e,c,k)}}}else d=window,a.fa&&d.pawsig&&typeof d.pawsig.clk==="function"?(Ue("paw_sigs",{msg:"click",count:a.K.toString(),elapsed:(Date.now()-a.u).toString()}),f&&d.pawsig.clk(c)):f&&(d=mf(c.href),d!==c.href&&Xa(c,Qe(d,Re(599))));f&&(a.P=Date.now());de(a.O)}
function Nf(a,b,c,d){if(!R(d,13)){var e=c.href;var h=/[?&]adurl=([^&]+)/.exec(e);e=h?[e.slice(0,h.index),e.slice(h.index)]:[e,""];for(Xa(c,Qe(e[0],Re(557)));!c.id;)if(h="asoch-id-"+(Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36)),!X.getElementById(h)){c.id=h;break}h=c.id;typeof window.xy==="function"&&window.xy(b,c,X.body);typeof window.mb==="function"&&window.mb(c);typeof window.bgz==="function"&&window.bgz(h);typeof window.ja===
"function"&&window.ja(h,d?nd(d,5):0);typeof window.vti==="function"&&window.vti(c);a.i&&typeof window.ss==="function"&&(a.X?window.ss(h,1,a.i):window.ss(a.i,1));if(e.length>0){var f;b=a.o.length>0&&(d==null||(f=Q(d,yd,26))==null||I(N(f,1))==null)?c.href+"&uach="+encodeURIComponent(a.o)+e[1]:c.href+e[1];Xa(c,Qe(b,Re(557)))}}}function Qf(a){Pd(Te(556,function(){new If(a||{})}))}function Lf(a,b){return $a(a,function(c){return c.element===b})}
function Jf(a){a=v(a);for(var b=a.next();!b.done;b=a.next()){var c=b.value;c.element.tagName=="A"&&(b=c.element,c=c.data,I(N(c,2))!=null||U(c,2,b.href))}};var Rf=Te(555,function(a){return Qf(a)});$d=70;var Sf=be(70,document.currentScript);if(Sf==null)throw Error("JSC not found 70");for(var Tf={},Uf=Sf.attributes,Vf=Uf.length-1;Vf>=0;Vf--){var Wf=Uf[Vf].name;Wf.indexOf("data-jcp-")===0&&(Tf[Wf.substring(9)]=Uf[Vf].value)}Rf(Tf);}).call(this);
